title: SuperMap iDesktop Cross 8C
subtitle: "跨平台、全开源、可定制"
description: "SuperMap iDesktop Cross 8C 是一款支持跨平台的桌面GIS应用与开发平台，是超图新一代的开源GIS桌面产品。"
author: iDesktop
language: zh
timezone: UTC
url: http://supermap-idesktop.github.io/SuperMap-iDesktop-Cross
root: /SuperMap-iDesktop-Cross/
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
highlight:
  enable: true
  line_number: false
per_page: 0

theme: navy
deploy:
  type: git
  repo: https://github.com/SuperMap-iDesktop/SuperMap-iDesktop-Cross.git
  branch: gh-pages

duoshuo_shortname: supermap-cross-support
duoshuo_share: true
google_analytics: UA-4910098-10
fb_admins: 100000247608790
algolia:
  github:
    api_key: 87c625ea3b3f57f243d590e3c59b0748
    index_name: supermap-idesktop
  localhost:
    api_key: 87c625ea3b3f57f243d590e3c59b0748
    index_name: supermap-idesktop
  support:
    api_key: 19f860b1fcffb4b23a7b2f928e8b0692
    index_name: supermap-cn
host:
  github: supermap-idesktop.github.io
  support: support.supermap.com.cn
# zh-cn:
#   api_key: cdea7d4e47d84f6145b77e7f68689f35
#   index_name: hexo_zh-cn
#twitter: qinlj
#github: qinlj/iDesktop-Cross-Docs
oschina: supermap/SuperMap-iDesktop-Cross
